accent = "#7dd2b8"
cursor = "#d4d5d5"
foreground = "#d4d5d5"
background = "#171a18"
selection_foreground = "#171a18"
selection_background = "#d4d5d5"

color0 = "#171a18"
color1 = "#7db085"
color2 = "#b8c082"
color3 = "#e0d480"
color4 = "#7dd2b8"
color5 = "#b5c9a4"
color6 = "#c5e8c5"
color7 = "#d4d5d5"
color8 = "#6b8071"
color9 = "#8cc098"
color10 = "#cdd590"
color11 = "#f2e590"
color12 = "#92e2c8"
color13 = "#c8dab8"
color14 = "#d8f5d8"
color15 = "#e2e3e3"
