# ────────────────────────────────────────────────────────────
# Custom Theme for Hyprlock
# ────────────────────────────────────────────────────────────

$color       = rgba(6, 13, 31, 1.0)
$inner_color = rgba(6, 13, 31, 1.0)
$outer_color = rgba(215, 235, 233, 1)
$font_color  = rgba(215, 235, 233, 1)
$check_color = rgba(242, 200, 203, 1)