
# ========= Border =========
file_panel_border = '#e1e9f5'
sidebar_border = '#e1e9f5'
footer_border = '#e1e9f5'

# ========= Border Active =========
file_panel_border_active = '#f7c3c6'
sidebar_border_active = '#f7c3c6'
footer_border_active = '#f7c3c6'
modal_border_active = '#f7c3c6'

# ========= Background (bg) =========
full_screen_bg = '#060d1f'
file_panel_bg = '#060d1f'
sidebar_bg = '#060d1f'
footer_bg = '#060d1f'
modal_bg = '#060d1f'

# ========= Foreground (fg) =========
full_screen_fg = '#E0F7FA'
file_panel_fg = '#E0F7FA'
sidebar_fg = '#E0F7FA'
footer_fg = '#E0F7FA'
modal_fg = '#E0F7FA'

# ========= Special Color =========
cursor = '#E0F7FA'
correct = '#6488EA'
error = '#e95c4b'
hint = '#fff6d2'
cancel = '#e95c4b'
gradient_color = ['#060d1f', "#51688E"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#060d1f'
file_panel_top_path = '#51688E'
file_panel_item_selected_fg = '#51688E'
file_panel_item_selected_bg = '#060d1f'

# ========= Sidebar Special Items =========
sidebar_title = '#c8cbd0'
sidebar_item_selected_fg = '#51688E'
sidebar_item_selected_bg = '#060d1f'
sidebar_divider = '#e1e9f5'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#e95c4b'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#6488EA'
